### ISSUE TITLE
How, uh, does this work?

### ISSUE THREAD

**Issue by chriscorwin** [macite/sublimebashbuildsystem#1]
Am I just an idiot?

I can't seem to figure out how to make this thing... go.

Help?

**Comment by macite** [comment]
Currently this will only work on Mac and Linux.

Make sure that the build system is set to Automatic, and that Bash is listed in the available Build Systems.

Open a bash script, and select Build from the Tools menu (or use keyboard shortcut). 

The file must be detected as a Shell Script (Bash) for this to automatically be selected.

Let me know if that helps.

cheers, Andrew

**Comment by macite** [comment]
Version 1.0.1 should now also work on Windows if you have MinGW on your path (or at C:\MinGW).
